version: "3" # composeファイルのバージョン
services:
  go:
    container_name: "tsuru-run"
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile # Dockerfileの場所
      target: dev # devステージをターゲットとする
    image: tsuru-run_go
    env_file:
      - ./docker/go/.env
    # tty: true
